### ISSUE TITLE
Character's position changes on reload

### ISSUE THREAD

**Issue by JSh-git** [1dot13/source#131]
Game Version: v0-3950-gff3601

Noticed it so far only with Blood. Let's say he stands on the corner of a building. Reloading might move him inside or to any of the surrounding tiles.

**Comment by vbmeireles** [comment]
I have the same happen, whenever I quick load (wth ALT+L), without fail, always to the first mercenary in my squad. Haven't tested with more than one squad in the same sector.

**Comment by Asdow** [comment]
Yeah, started noticing the same upon quickload

**Comment by Asdow** [comment]
Okay, it happens in NewOKDestination() function call at line 1234 in soldier add.cpp
We check  for the tile the merc is on and it returns FALSE when it fails the check on line 5098 in overhead.cpp ... because we're standing on it already.

git blame shows both of these codes to be over 10 years old, and I have no idea why it's not been doing this constantly all these years and why it doesn't happen to all the mercs when loading a save

adding a return true clause like this before the multitile check on line 5098 keeps the merc in its proper place, but I don't know yet if it causes some other unintended effect as the function is used extensively in the code.

`        // If this tile is our current tile
        if (bPerson == pCurrSoldier->ubID && sGridNo == pCurrSoldier->sGridNo)
        {
            return(TRUE);
        }
`
