### ISSUE TITLE
Pablo speech files delayed package

### ISSUE THREAD

**Issue by kitty624** [1dot13/source#181]
A report about Pablos speech files 11 and 25 not triggering (package still in transit, loyality to low)

and 14 and 15 not having a trigger in npc-script although wav exists

(pablo is 98.npc)

**Comment by rftrdev** [comment]
I think this is about Pablo only having a single voiceline for all BR deliveries - the "small package" one. He's supposed to have variant lines for medium (10kg+?) and large (20kg+?) shipments but only ever plays the "small package" line.

I haven't confirmed what happens when a BR shipment is sent back due to low loyalty in Drassen.

**Comment by sevenfm** [comment]
Facts FACT_MEDIUM_SIZED_SHIPMENT_WAITING and FACT_LARGE_SIZED_SHIPMENT_WAITING are never set in new shipment code, if you define them in CPostalService::DeliverShipment() as they were in original game

> // set fact according to shipment size
> 		if (usNumberOfItems - uiStolenCount <= 5)
> 		{
> 			SetFactFalse(FACT_MEDIUM_SIZED_SHIPMENT_WAITING);
> 			SetFactFalse(FACT_LARGE_SIZED_SHIPMENT_WAITING);
> 		}
> 		else if (usNumberOfItems - uiStolenCount <= 15)
> 		{
> 			SetFactTrue(FACT_MEDIUM_SIZED_SHIPMENT_WAITING);
> 			SetFactFalse(FACT_LARGE_SIZED_SHIPMENT_WAITING);
> 		}
> 		else
> 		{
> 			SetFactFalse(FACT_MEDIUM_SIZED_SHIPMENT_WAITING);
> 			SetFactTrue(FACT_LARGE_SIZED_SHIPMENT_WAITING);
> 		}

Pablo will use quote based on shipment size when talked about new delivery.

**Comment by rftrdev** [comment]
Thanks Seven! We'll get this in.
