### ISSUE TITLE
Loading a save causes a bug, newest version

### ISSUE THREAD

**Issue by TafferKubrick** [1dot13/source#217]
Using the latest version, released yesterday at time of writing. Game freezes very often during load of a save, almost to the point of making it unplayable. Just in case it's me screwing something up, I'm leaving my JAOptions.ini as I've edited it (turned into a .txt for Github upload only). Game is not letting me know of any issues at boot (like a wrong number, etc) tho, as it usually does if there is something wrong. Here's my save files too, it happens both with hard saves and autosaves.

[Ja2_Options.txt](https://github.com/1dot13/source/files/12493917/Ja2_Options.txt)
[SavedGames.zip](https://github.com/1dot13/source/files/12493937/SavedGames.zip)

**Comment by TafferKubrick** [comment]
Okay, cool. I'm sorry I don't know how this works, I opened up a Github account just for this. Should I just wait for a new version?

**Comment by andrzejfalkowski** [comment]
@kitty624 Hey, I checked on my side since I got few PRs merged lately so I might've introduced it, I'm getting around 10% repro rate when spamming quickload, read access violation exception in RebelCommand from

```
// coolness runs from 1-10, so apply offset
ItemIdCache::ammo[Item[i].ubCoolness-1].push_back(i);
```

Item 1515 .30 Car Box has no coolness set in Items.xml, it defaults to 0, so it's ItemIdCache::ammo[-1].push_back(i);, in C# you'd get nice IndexOutOfRangeException first time you try that but in C++ it can apparently go through most of the time (who knows what happens in the memory, probably nothing good). 30 Car Box should have coolness of at least 1, or Item[i].ubCoolness-1 should be clamped to 0 in code. I checked with coolness 1 and no more repro.

**Comment by rftrdev** [comment]
I'll take care of this one

**Comment by TafferKubrick** [comment]
I see the latest release is the one bugged out. Will there be a new one coming out soon or do you guys take some months in between? It's no issue for me, I just want to know what should I do.

**Comment by rftrdev** [comment]
Latest unstable should have the fix and is available: https://github.com/1dot13/source/releases/tag/latest

**Comment by TafferKubrick** [comment]
Oh sorry, thanks. I should not use savegames from the bugged version, right?

**Comment by rftrdev** [comment]
The save itself is probably fine. Try it out :)

**Comment by TafferKubrick** [comment]
Everything works great now, thank you all!
