### ISSUE TITLE
Missing graphics?

### ISSUE THREAD

**Issue by n9103** [1dot13/source#299]
Typed out the error from game.
> Assertion Failure [Line 1952 in file D:\a\source\source\Laptop\BobbyRGuns.cpp]. 
> Error: Could not load item uiIndex 335 graphics. ubGraphicType 1 and ubGraphicNum 726
I was scrolling to the end of Bobby's catalog, gun category, when this hit.

**Comment by n9103** [comment]
Version is 134 (latest from a few days ago I think?).
Didn't see any other issues reporting a missing graphic, or anything that hit on Num 726, so assume mine is still present.

**Comment by Asdow** [comment]
I remember someone else having a CTD related to the other, gray barrett graphics when playing JA2 Vanilla VFS config. Maybe this is a similar situation?

**Comment by Asdow** [comment]
@kitty624 This is definitely a vanilla JA2 config issue. If you enable VFS_CONFIG_INI = vfs_config.JA2Vanilla.ini in ja2.ini, the game will error out in Bobby Ray's due to not being able to find the big item graphics. It will *also* crash in tactical because the mdp1items.sti does not have the proper subimages for the weapon.

**Comment by n9103** [comment]
Sorry for not getting back to this earlier.
I don't have the save anymore, but as best I can recall, I had the BR quality maxed out, specifically so I could do a Barrett run.

**Comment by Asdow** [comment]
Fixed by gamedir commit https://github.com/1dot13/gamedir/commit/a57876d5075475eab4d67ee642fb99a02e1af86a

**Comment by n9103** [comment]
AwesomeOn Aug 6, 2024 11:35 AM, Asdow ***@***.***> wrote:
Closed #299 as completed.
