### ISSUE TITLE
Patient assignment broken when food system enabled. 

### ISSUE THREAD

**Issue by logunovFGP** [1dot13/source#314]
Cannot set patient assignment if stats were lost due to hungry after reload the game, however can do so if jump through window and healing of the stats starts as expected, it only allows to set patient assignment if food AND water (both) above 100% (the merc overfed), while expected values are above 90% (the merc not hunger).

![image](https://github.com/user-attachments/assets/22784996-cf42-43cd-bbf9-7df37ccb1148)

**Comment by Asdow** [comment]
There is a check on line 1565 in Assignments.cpp which checks whether the merc's food and water satiety levels are above normal. I tested doctoring a merc who has stat loss due to hunger, by injuring them a bit and setting them as patient. Only the damaged health due to jumping through a window was healed.


Based on that, I think a merc with starvation induced stat loss is meant to be allowed as a patient and recover those lost points only if they are well fed, and this is intended behavior.

**Comment by logunovFGP** [comment]
@Asdow the problem of this issue is not in definition. Well fed must be counter as 90% and above, not 100% and above. 90% is a well-fed merc, you are expecting that the merc which is not suffering starvation can be assigned to the patient task, however it cannot, which is counter-intuitive that the merc must be OVERfed instead of well-fed.
