### ISSUE TITLE
Languages beside English are broken

### ISSUE THREAD

**Issue by Asdow** [1dot13/source#98]
At the very least Polish build crashes without exception upon encountering enemies after the first fight, with a "video object index is larger than number of subimages" assertion error. This one points to an outdated .sti file somewhere in the Polish gamedir.

We're *also* getting intermittent assertion failures in arms dealer init.cpp, line 1166: GetArmsDealerItemTypeFromItemNumber(), invalid class 0 for item 1762.adf 0.

**Comment by Asdow** [comment]
It almost makes me think some loop has a wrong ending condition where it's comparing i >= number of items, which would loop one time extra and then it's used to read item info and fails, 'cause we have no item 1762.

Though, why would it come up only occasionally and not always is odd

**Comment by Asdow** [comment]
Yeah, I fixed it today when another guy on discord asked about it. Might just not have been updated into the latest release when you downloaded

**Comment by Asdow** [comment]
Once the latest release updates and includes the xml encoding fix for French language, all languages should be playable, so I'm gonna close this already.

**Comment by dpapadam** [comment]
I'm wondering if this had anything to do with my 'disappearing items'. As I feel I have perhaps narrowed it down to the fact that it's the FIRST group you face when your mercs land. They don't seem to drop items the regular army does. So I'm wondering if that first group (welcome wagon group) is something special and perhaps THOSE are the items that are disappearing and we're getting confused because it mixes with everything else.. Just a sidenote in case I see the ticket is closed.
